LOGIN = "LOGIN"
LOGIN_OK = "LOGIN_OK"

LISTAR_PARTIDAS = "LISTAR_PARTIDAS"
PARTIDAS_DISPONIBLES = "PARTIDAS_DISPONIBLES"

CREAR_PARTIDA = "CREAR_PARTIDA"
PARTIDA_CREADA = "PARTIDA_CREADA"

UNIR_PARTIDA = "UNIR_PARTIDA"
UNIDO_A_PARTIDA = "UNIDO_A_PARTIDA"

CHAT_GENERAL = "MENSAJE_GENERAL"
CHAT_SALA = "CHAT_SALA"

CAMBIAR_LISTO = "CAMBIAR_LISTO"
ESTADO_SALA = "ESTADO_SALA"

INICIAR_PARTIDA = "INICIAR_PARTIDA"
CAMBIO_TURNO = "CAMBIO_TURNO"

LANZAR_DADO = "LANZAR_DADO"
RESULTADO_DADO = "RESULTADO_DADO"

MOVER_FICHA = "MOVER_FICHA"
ESTADO_FICHAS = "ESTADO_FICHAS"

ERROR = "ERROR"
